### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by Cryopier** [lauenchr/elvui-kotja-datatexts#1]
I've tried adding it to the addons folder like normal addons.  I've even copied the LUA files into the Core/Datatexts folder for ElvUI itself.  Can't seem to get it working.

**Comment by lauenchr** [comment]
You install it as its own addon. So basically unzip it and copy it to the AddOns folder
![image](https://user-images.githubusercontent.com/47520341/190895173-03ef1356-1be8-4b37-b763-1168cf39327d.png)
Or use an AddOn manager like WoWUp (which I use) and you can install it from url by using https://github.com/lauenchr/elvui-kotja-datatexts/releases as the url
